import os
from io import BytesIO
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from django.conf import settings
from django.http import HttpResponse
from datetime import datetime
import math

# Register multilingual fonts
def register_fonts():
    """Register multilingual fonts for PDF generation"""
    try:
        # Try to register Arial Unicode MS for full Unicode support
        pdfmetrics.registerFont(TTFont('ArialUnicode', 'arialuni.ttf'))
        return 'ArialUnicode'
    except:
        try:
            # Fallback to DejaVu Sans which supports many languages
            pdfmetrics.registerFont(TTFont('DejaVuSans', 'DejaVuSans.ttf'))
            return 'DejaVuSans'
        except:
            try:
                # Fallback to FreeSans
                pdfmetrics.registerFont(TTFont('FreeSans', 'FreeSans.ttf'))
                return 'FreeSans'
            except:
                # Use default Helvetica (limited Unicode support)
                return 'Helvetica'

# Call this function once when the module loads
FONT_NAME = register_fonts()

def generate_sales_report_pdf(context):
    """Generate PDF sales report using ReportLab with multilingual support"""
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer, 
            pagesize=A4, 
            topMargin=0.5*inch, 
            bottomMargin=0.5*inch,
            leftMargin=0.5*inch,
            rightMargin=0.5*inch
        )
        
        # Get styles
        styles = getSampleStyleSheet()
        
        # Create custom styles with multilingual font support
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontName=FONT_NAME,
            fontSize=14,
            spaceAfter=20,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#2c3e50')
        )
        
        company_style = ParagraphStyle(
            'CompanyStyle',
            parent=styles['Heading2'],
            fontName=FONT_NAME,
            fontSize=16,
            spaceAfter=10,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#34495e')
        )
        
        subtitle_style = ParagraphStyle(
            'SubtitleStyle',
            parent=styles['Heading3'],
            fontName=FONT_NAME,
            fontSize=12,
            spaceAfter=15,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#7f8c8d')
        )
        
        info_style = ParagraphStyle(
            'InfoStyle',
            parent=styles['Normal'],
            fontName=FONT_NAME,
            fontSize=9,
            spaceAfter=3,
            alignment=TA_LEFT
        )
        
        normal_style = ParagraphStyle(
            'CustomNormal',
            parent=styles['Normal'],
            fontName=FONT_NAME,
            fontSize=9,
            spaceAfter=6
        )
        
        # Build the story (content)
        story = []
        
        # Company Header - Multilingual support
        company_name = context.get('company_name', 'SHOP MANAGEMENT SYSTEM')
        report_title = context.get('report_title', 'SALES REPORT')
        
        story.append(Paragraph(company_name, company_style))
        story.append(Paragraph(report_title, title_style))
        
        # Report Information
        current_datetime = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        story.append(Paragraph(f"Generated on: {current_datetime}", subtitle_style))
        
        # Report Details
        report_type = context.get('report_type', 'daily').replace('_', ' ').title()
        date_info = get_date_range_info(context)
        
        details_data = [
            [Paragraph("<b>Report Type:</b>", info_style), Paragraph(report_type, info_style)],
            [Paragraph("<b>Date Range:</b>", info_style), Paragraph(date_info, info_style)],
        ]
        
        # Add filters information
        filters_info = get_filters_info(context)
        if filters_info:
            details_data.append([Paragraph("<b>Filters:</b>", info_style), Paragraph(filters_info, info_style)])
        
        # Add generated by information
        generated_by = context.get('request_user', 'System')
        details_data.append([Paragraph("<b>Generated By:</b>", info_style), Paragraph(generated_by, info_style)])
        
        details_table = Table(details_data, colWidths=[1.5*inch, 4*inch])
        details_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
        ]))
        
        story.append(details_table)
        story.append(Spacer(1, 15))
        
        # Get report format and sales data
        report_format = context.get('report_format', 'detailed')
        sales = context.get('sales', [])
        
        # Sales Data Table based on report format
        if report_format == 'summary':
            story.append(Paragraph("SALES SUMMARY", subtitle_style))
            summary_table = create_summary_table(context)
            if summary_table:
                story.append(summary_table)
            else:
                story.append(Paragraph("No sales data available for the selected period.", normal_style))
            
            # ADD SUMMARY STATISTICS AFTER THE SUMMARY TABLE
            story.append(Spacer(1, 15))
            story.append(Paragraph("SUMMARY STATISTICS", subtitle_style))
            summary_stats = create_summary_stats_table(context)
            if summary_stats:
                story.append(summary_stats)
            
        else:  # detailed report
            story.append(Paragraph("DETAILED SALES TRANSACTIONS", subtitle_style))
            detailed_table = create_detailed_table(context)
            if detailed_table:
                story.append(detailed_table)
            else:
                story.append(Paragraph("No sales transactions found for the selected criteria.", normal_style))
        
        story.append(Spacer(1, 15))
        
        # Footer with multilingual support
        footer_text = context.get('footer_text', 'Shop Management System - Confidential Report')
        footer_style = ParagraphStyle(
            'FooterStyle',
            parent=styles['Normal'],
            fontName=FONT_NAME,
            fontSize=8,
            textColor=colors.HexColor('#7f8c8d'),
            alignment=TA_CENTER
        )
        story.append(Paragraph(footer_text, footer_style))
        
        # Build PDF with page break support
        def add_page_number(canvas, doc):
            """Add page numbers to each page"""
            page_num = canvas.getPageNumber()
            text = f"Page {page_num}"
            canvas.setFont(FONT_NAME, 8)
            canvas.setFillColor(colors.HexColor('#7f8c8d'))
            canvas.drawRightString(doc.pagesize[0] - 0.5*inch, 0.4*inch, text)
            
            # Add footer text on each page
            canvas.setFont(FONT_NAME, 7)
            canvas.drawString(0.5*inch, 0.4*inch, footer_text)
        
        # Build PDF with page number callback
        doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
        
        # Get PDF value from buffer
        pdf = buffer.getvalue()
        buffer.close()
        return pdf
        
    except Exception as e:
        print(f"PDF generation error: {str(e)}")
        import traceback
        traceback.print_exc()  # This will print the full traceback
        # Return a simple PDF with error message
        return create_error_pdf(str(e))

def create_error_pdf(error_message):
    """Create a simple PDF with error message"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    story = []
    
    styles = getSampleStyleSheet()
    error_style = ParagraphStyle(
        'ErrorStyle',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=colors.red,
        alignment=TA_CENTER
    )
    
    story.append(Paragraph("PDF Generation Error", error_style))
    story.append(Paragraph(f"Error: {error_message}", styles['Normal']))
    
    doc.build(story)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf

def create_summary_stats_table(context):
    """Create summary statistics table"""
    
    # Calculate total actual paid from sales data (paid_amount - change_amount)
    sales = context.get('sales', [])
    total_actual_paid = sum(
        max(0, float(sale.paid_amount or 0) - float(sale.change_amount or 0)) 
        for sale in sales
    )
    
    stats_data = [
        ["Total Transactions:", f"{context.get('total_transactions', 0):,}"],
        ["Gross Sales:", format_currency(context.get('gross_sales', 0), context.get('currency_symbol', '৳'))],
        ["Returns:", format_currency(context.get('total_returns', 0), context.get('currency_symbol', '৳'))],
        ["Net Sales:", format_currency(context.get('net_sales', 0), context.get('currency_symbol', '৳'))],
        ["Total Due Amount:", format_currency(context.get('total_due_amount', 0), context.get('currency_symbol', '৳'))],
        ["Total Paid Amount:", format_currency(total_actual_paid, context.get('currency_symbol', '৳'))],  # Use actual paid
        ["Total Items Sold:", f"{context.get('total_items_sold', 0):,}"],
        ["Items Returned:", f"{context.get('total_items_returned', 0):,}"],
        ["Net Items Sold:", f"{context.get('net_items_sold', 0):,}"],
        ["Average Sale:", format_currency(context.get('average_sale', 0), context.get('currency_symbol', '৳'))],
    ]
    
    data = [[Paragraph("<b>Metric</b>", getSampleStyleSheet()['Normal']), 
             Paragraph("<b>Value</b>", getSampleStyleSheet()['Normal'])]] + stats_data
    
    table = Table(data, colWidths=[2.5*inch, 2*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('FONTNAME', (0, 1), (-1, -1), FONT_NAME),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('ALIGN', (0, 1), (0, -1), 'LEFT'),
        ('ALIGN', (1, 1), (1, -1), 'RIGHT'),
        
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    return table

def get_date_range_info(context):
    """Generate date range information string with multilingual support"""
    date_range = context.get('date_range', 'today')
    start_date = context.get('start_date')
    end_date = context.get('end_date')
    today = context.get('today')
    
    # Multilingual date range labels
    date_labels = {
        'today': 'Today',
        'yesterday': 'Yesterday', 
        'this_week': 'This Week',
        'last_week': 'Last Week',
        'this_month': 'This Month',
        'last_month': 'Last Month',
        'custom': 'Custom Range'
    }
    
    if date_range == 'custom' and start_date and end_date:
        return f"{start_date} to {end_date}"
    elif date_range == 'today':
        return f"{date_labels['today']} ({today})"
    elif date_range == 'yesterday':
        return f"{date_labels['yesterday']} ({today})"
    elif date_range == 'this_week':
        return f"{date_labels['this_week']} (up to {today})"
    elif date_range == 'last_week':
        return date_labels['last_week']
    elif date_range == 'this_month':
        return f"{date_labels['this_month']} (up to {today})"
    elif date_range == 'last_month':
        return date_labels['last_month']
    else:
        return f"Date: {today}"

def get_filters_info(context):
    """Generate filters information string with multilingual support"""
    filters = []
    
    # Multilingual filter labels
    labels = {
        'product': 'Product',
        'category': 'Category', 
        'sales_person': 'Sales Person',
        'company': 'Company',
        'all': 'All'
    }
    
    if context.get('selected_product'):
        filters.append(f"{labels['product']}: {context['selected_product'].name}")
    
    if context.get('selected_category'):
        filters.append(f"{labels['category']}: {context['selected_category'].name}")
    
    if context.get('selected_user'):
        user = context['selected_user']
        filters.append(f"{labels['sales_person']}: {user.get_full_name() or user.username}")
    else:
        filters.append(f"{labels['sales_person']}: {labels['all']}")
    
    if context.get('company') and context['company'] != 'main':
        filters.append(f"{labels['company']}: {context['company']}")
    
    return " | ".join(filters) if filters else f"{labels['all']} Records"

def safe_text(text, max_length=30):
    """Ensure text is safe for PDF and handle multilingual characters"""
    if text is None:
        return ""
    
    # Convert to string and handle encoding
    text = str(text)
    
    # Truncate if too long
    if len(text) > max_length:
        text = text[:max_length-3] + "..."
    
    return text

def format_currency(amount, currency_symbol='৳'):
    """Format currency with symbol support"""
    try:
        amount_float = float(amount)
        return f"{currency_symbol}{amount_float:,.2f}"
    except (ValueError, TypeError):
        return f"{currency_symbol}0.00"

def create_summary_table(context):
    """Create summary table with multilingual support"""
    sales = context.get('sales', [])
    
    if not sales:
        return None
    
    # Multilingual column headers - REMOVED: 'Net Items Sold' column
    headers = [
        'S/N', 'Date', 'Gross Sales', 'Discount', 'Tax', 'Net Sales',
        'Due Amount', 'Paid Amount', 'Returns', 'Sales Person'  # REMOVED 'Net Items Sold'
    ]
    
    # Prepare table data
    data = [headers]
    
    # Group sales by date for summary view
    sales_by_date = {}
    for sale in sales:
        sale_date = sale.sale_date.date()
        if sale_date not in sales_by_date:
            sales_by_date[sale_date] = {
                'gross_sales': 0,
                'discount': 0,
                'tax': 0,
                'net_sales': 0,
                'due_amount': 0,
                'paid_amount': 0,  # This will now store actual paid (paid_amount - change_amount)
                'returns': 0,
                'sales_persons': set()
            }
        
        sales_by_date[sale_date]['gross_sales'] += float(sale.total_amount or 0)
        sales_by_date[sale_date]['discount'] += float(sale.discount_amount or 0)
        sales_by_date[sale_date]['tax'] += float(sale.tax_amount or 0)
        sales_by_date[sale_date]['net_sales'] += float(sale.net_amount or 0)
        sales_by_date[sale_date]['due_amount'] += float(sale.remaining_due or 0)
        
        # CHANGE: Use actual paid amount (paid_amount - change_amount) instead of just paid_amount
        actual_paid = float(sale.paid_amount or 0) - float(sale.change_amount or 0)
        sales_by_date[sale_date]['paid_amount'] += max(0, actual_paid)  # Ensure not negative
        
        sales_by_date[sale_date]['returns'] += float(sale.returned_amount or 0)
        sales_by_date[sale_date]['sales_persons'].add(safe_text(sale.sold_by.username))
    
    # Add rows for each date
    sn = 1
    currency_symbol = context.get('currency_symbol', '৳')
    for date, summary in sorted(sales_by_date.items()):
        sales_person = ', '.join(summary['sales_persons']) if len(summary['sales_persons']) <= 2 else 'Multiple'
        
        data.append([
            str(sn),
            date.strftime("%Y-%m-%d"),
            format_currency(summary['gross_sales'], currency_symbol),
            format_currency(summary['discount'], currency_symbol),
            format_currency(summary['tax'], currency_symbol),
            format_currency(summary['net_sales'], currency_symbol),
            format_currency(summary['due_amount'], currency_symbol),
            format_currency(summary['paid_amount'], currency_symbol),  # This now shows actual paid
            format_currency(summary['returns'], currency_symbol),
            safe_text(sales_person, 15)
        ])
        sn += 1
    
    # Add totals row
    total_gross = sum(item['gross_sales'] for item in sales_by_date.values())
    total_discount = sum(item['discount'] for item in sales_by_date.values())
    total_tax = sum(item['tax'] for item in sales_by_date.values())
    total_net = sum(item['net_sales'] for item in sales_by_date.values())
    total_due = sum(item['due_amount'] for item in sales_by_date.values())
    total_paid = sum(item['paid_amount'] for item in sales_by_date.values())  # This now shows actual total paid
    total_returns = sum(item['returns'] for item in sales_by_date.values())
    
    data.append([
        '', 'TOTALS:',
        format_currency(total_gross, currency_symbol),
        format_currency(total_discount, currency_symbol),
        format_currency(total_tax, currency_symbol),
        format_currency(total_net, currency_symbol),
        format_currency(total_due, currency_symbol),
        format_currency(total_paid, currency_symbol),  # This now shows actual total paid
        format_currency(total_returns, currency_symbol),
        ''
    ])
    
    # Create table with appropriate column widths - ADJUSTED for removed column
    col_widths = [0.4*inch, 0.8*inch, 0.9*inch, 0.7*inch, 0.6*inch, 0.9*inch, 0.8*inch, 0.8*inch, 0.7*inch, 1.2*inch]
    
    table = Table(data, colWidths=col_widths, repeatRows=1)
    
    # Define table style - UPDATED column ranges
    style = TableStyle([
        # Header row
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 7),
        
        # Data rows
        ('BACKGROUND', (0, 1), (-1, -2), colors.HexColor('#ffffff')),
        ('TEXTCOLOR', (0, 1), (-1, -2), colors.black),
        ('FONTNAME', (0, 1), (-1, -2), FONT_NAME),
        ('FONTSIZE', (0, 1), (-1, -2), 6),
        ('ALIGN', (0, 1), (0, -2), 'CENTER'),  # S/N column
        ('ALIGN', (2, 1), (8, -2), 'RIGHT'),   # Amount columns (updated range)
        
        # Totals row
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#34495e')),
        ('TEXTCOLOR', (0, -1), (-1, -1), colors.whitesmoke),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, -1), (-1, -1), 7),
        ('ALIGN', (2, -1), (8, -1), 'RIGHT'),  # Updated range for totals
        
        # Grid
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#bdc3c7')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ])
    
    table.setStyle(style)
    return table

def create_detailed_table(context):
    """Create detailed sales transactions table with multilingual support"""
    sales = context.get('sales', [])
    
    if not sales:
        return None
    
    # Multilingual column headers - REMOVED: 'Items Sold' column
    headers = [
        'S/N', 'Date', 'Invoice No', 'Customer', 'Gross Sales', 
        'Discount', 'Tax', 'Net Sales', 'Due Amount', 'Paid Amount', 'Sold By'  # REMOVED 'Items Sold'
    ]
    
    # Prepare table data
    data = [headers]
    
    sn = 1
    currency_symbol = context.get('currency_symbol', '৳')
    for sale in sales:
        customer_name = safe_text(sale.customer_name or "Walk-in Customer", 20)
        invoice_number = safe_text(sale.invoice_number[-8:], 8) if sale.invoice_number else "N/A"
        sold_by = safe_text(sale.sold_by.username, 15)
        
        # CHANGE: Calculate actual paid amount for each sale
        actual_paid = float(sale.paid_amount or 0) - float(sale.change_amount or 0)
        actual_paid = max(0, actual_paid)  # Ensure not negative
        
        data.append([
            str(sn),
            sale.sale_date.strftime("%Y-%m-%d"),
            invoice_number,
            customer_name,
            format_currency(sale.total_amount, currency_symbol),
            format_currency(sale.discount_amount, currency_symbol),
            format_currency(sale.tax_amount, currency_symbol),
            format_currency(sale.net_amount, currency_symbol),
            format_currency(sale.remaining_due, currency_symbol),
            format_currency(actual_paid, currency_symbol),  # Use actual paid instead of paid_amount
            sold_by
        ])
        sn += 1
    
    # Add totals row - recalculate with actual paid amounts
    total_gross = sum(float(sale.total_amount or 0) for sale in sales)
    total_discount = sum(float(sale.discount_amount or 0) for sale in sales)
    total_tax = sum(float(sale.tax_amount or 0) for sale in sales)
    total_net = sum(float(sale.net_amount or 0) for sale in sales)
    total_due = sum(float(sale.remaining_due or 0) for sale in sales)
    
    # CHANGE: Calculate total actual paid (sum of all actual paid amounts)
    total_paid = sum(
        max(0, float(sale.paid_amount or 0) - float(sale.change_amount or 0)) 
        for sale in sales
    )
    
    data.append([
        '', '', '', 'TOTALS:',
        format_currency(total_gross, currency_symbol),
        format_currency(total_discount, currency_symbol),
        format_currency(total_tax, currency_symbol),
        format_currency(total_net, currency_symbol),
        format_currency(total_due, currency_symbol),
        format_currency(total_paid, currency_symbol),  # This now shows actual total paid
        ''
    ])
    
    # Create table with appropriate column widths - ADJUSTED for removed column
    col_widths = [0.3*inch, 0.6*inch, 0.8*inch, 1.0*inch, 0.8*inch, 0.7*inch, 0.6*inch, 0.8*inch, 0.7*inch, 0.7*inch, 0.9*inch]
    
    table = Table(data, colWidths=col_widths, repeatRows=1)
    
    # Define table style - UPDATED column ranges
    style = TableStyle([
        # Header row
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 6),
        
        # Data rows
        ('BACKGROUND', (0, 1), (-1, -2), colors.HexColor('#ffffff')),
        ('TEXTCOLOR', (0, 1), (-1, -2), colors.black),
        ('FONTNAME', (0, 1), (-1, -2), FONT_NAME),
        ('FONTSIZE', (0, 1), (-1, -2), 5.5),
        ('ALIGN', (0, 1), (0, -2), 'CENTER'),  # S/N column
        ('ALIGN', (4, 1), (9, -2), 'RIGHT'),   # Amount columns (updated range)
        
        # Totals row
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#34495e')),
        ('TEXTCOLOR', (0, -1), (-1, -1), colors.whitesmoke),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, -1), (-1, -1), 6),
        ('ALIGN', (4, -1), (9, -1), 'RIGHT'),  # Updated range for totals
        
        # Grid
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#bdc3c7')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ])
    
    table.setStyle(style)
    return table

def create_pdf_response(pdf_content, filename):
    """Create HTTP response with PDF content"""
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    response.write(pdf_content)
    return response